### PR TITLE
add endpoint configuration for aws s3 to be used in yandex s3

### LINKED ISSUE #89: AWS S3 set endpoint to be used in yandex s3
Hi

In order to be possible use yandex S3 (who mimic the S3 API in everything except the endpoint)

I'd like to be able to set the endpoint in the cloudstorage Conf

to be used only in awss3 if it is not empty

https://cloud.yandex.com/en/docs/storage/s3/

### PR DESCRIPTION
**Pull request by peczenyj**
In theory, this can give me access to Yandex S3 API

### CODE REVIEW

**Comment by peczenyj** [comment]
closes #89

**Comment by peczenyj** [comment]
BTW I test this with a real yandex S3 bucket and everything works

another option is to create a yandexs3 package with 99.9 % of the code equal to awss3 but I think it is overkill

**Comment by epsniff** [comment]
@peczenyj sorry I just noticed this PR.  Ill get it reviewed soon.

**Review by epsniff — APPROVED** [review]

**Comment by peczenyj** [comment]
Thanks

**Comment by peczenyj** [comment]
> @peczenyj sorry I just noticed this PR. Ill get it reviewed soon.

How about release a new version of cloudstorage?

**Pull request merged**
